# Generated by Django 3.1.4 on 2021-06-07 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='posters/')),
                ('singer', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.city')),
            ],
        ),
    ]
