# Generated by Django 3.1.4 on 2021-06-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.TextField(default='', max_length=100),
        ),
    ]
