# Generated by Django 3.1.4 on 2021-06-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.URLField(),
        ),
    ]
