# Generated by Django 3.1.4 on 2021-06-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(choices=[('Dnipro', 'Dnipro'), ('Kyiv', 'Kyiv'), ('Kharkiv', 'Kharkiv')], max_length=100),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
