# Generated by Django 3.1.4 on 2021-06-15 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210616_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='singer',
            new_name='headliner',
        ),
    ]
