# Generated by Django 3.1.4 on 2021-06-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210616_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
