# Generated by Django 3.1.4 on 2021-06-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210616_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='catergory',
            field=models.CharField(choices=[('concerts', 'concerts'), ('theater', 'theater'), ('kids', 'kids'), ('festivals', 'festivals'), ('humor', 'humor')], max_length=100),
        ),
    ]
