# Generated by Django 3.1.4 on 2021-06-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210617_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='catergory',
            new_name='category',
        ),
    ]
