# Generated by Django 3.1.4 on 2021-06-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20210618_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='popular',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], max_length=10),
        ),
    ]
