# Generated by Django 3.1.4 on 2021-06-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210618_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='popular',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10),
        ),
    ]
