# Generated by Django 3.1.4 on 2021-06-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20210618_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='popular',
            field=models.BooleanField(),
        ),
    ]
