# Generated by Django 3.1.4 on 2021-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20210618_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='event',
            name='carousel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
