# Generated by Django 3.1.4 on 2021-08-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_order_subscribeemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='event',
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ManyToManyField(to='events.Event'),
        ),
    ]
