# Generated by Django 3.1.4 on 2021-08-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20210803_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='asd19@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Alex', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=974391603),
        ),
    ]
