# Generated by Django 3.1.4 on 2021-08-02 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20210803_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='event',
            new_name='events',
        ),
    ]
