# Generated by Django 3.1.4 on 2021-09-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20210803_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='month',
            field=models.CharField(choices=[('january', 'january'), ('february', 'february'), ('march', 'march'), ('april', 'april'), ('may', 'may'), ('june', 'june'), ('july', 'july'), ('august', 'august'), ('september', 'september'), ('october', 'october'), ('november', 'november'), ('december', 'december')], default='january', max_length=100),
        ),
    ]
