# Generated by Django 3.1.4 on 2021-09-09 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
