# Generated by Django 3.1.4 on 2021-09-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
